[theme]
# プライマリカラー
primaryColor = "#FF6B6B"

# 背景色
backgroundColor = "#FFFFFF"

# セカンダリ背景色
secondaryBackgroundColor = "#F0F2F6"

# テキストカラー
textColor = "#262730"

# フォント
font = "sans serif"

[server]
# ファイルアップロードの最大サイズ（MB）
maxUploadSize = 200

# メッセージの最大サイズ（MB）
maxMessageSize = 200

# XSRF保護を無効化（Squadbase環境での動作のため）
# 注意: 本番環境では true に設定してください
enableXsrfProtection = false

# CORS保護を無効化（Squadbase環境での動作のため）
# 注意: 本番環境では true に設定してください
enableCORS = false

# ファイルウォッチャーのタイプ
fileWatcherType = "none"

# WebSocketの設定を追加
enableWebsocketCompression = false

# ベースパス（リバースプロキシ配下での衝突回避）
# デプロイ後は https://<domain>/tri-merger にアクセスしてください
baseUrlPath = "tri-merger"

[browser]
# タブのタイトル
gatherUsageStats = false
